### ISSUE TITLE
IndexError: too many indices for array?

### ISSUE THREAD

**Issue by robeson1010** [neptune-ml/open-solution-mapping-challenge#157]
When I run the train process, if shows:

`2018-07-01 22-26-13 mapping-challenge >>> training
neptune: Executing in Offline Mode.
neptune: Executing in Offline Mode.
2018-07-01 22-26-17 steps >>> step xy_train adapting inputs
2018-07-01 22-26-17 steps >>> step xy_train transforming...
2018-07-01 22-26-17 steps >>> step xy_inference adapting inputs
2018-07-01 22-26-17 steps >>> step xy_inference transforming...
2018-07-01 22-26-17 steps >>> step loader adapting inputs
2018-07-01 22-26-17 steps >>> step loader transforming...
2018-07-01 22-26-17 steps >>> step unet unpacking inputs
2018-07-01 22-26-17 steps >>> step unet fitting and transforming...
2018-07-01 22-26-21 steps >>> starting training...
2018-07-01 22-26-21 steps >>> initial lr: 0.0005
2018-07-01 22-26-21 steps >>> epoch 0 ...
2018-07-01 22-26-22 steps >>> epoch 0 batch 0 ...
Traceback (most recent call last):
  File "main.py", line 93, in <module>
    main()
  File "/home/user/miniconda2/envs/py3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/miniconda2/envs/py3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/user/miniconda2/envs/py3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/miniconda2/envs/py3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/miniconda2/envs/py3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 31, in train
    pipeline_manager.train(pipeline_name, dev_mode)
  File "/home/user/robeson/unet/tensorX/open/open-solution-mapping-challenge-solution-6/src/pipeline_manager.py", line 32, in train
    train(pipeline_name, dev_mode, self.logger, self.params, self.seed)
  File "/home/user/robeson/unet/tensorX/open/open-solution-mapping-challenge-solution-6/src/pipeline_manager.py", line 115, in train
    pipeline.fit_transform(data)
  File "/home/user/robeson/unet/tensorX/open/open-solution-mapping-challenge-solution-6/src/steps/base.py", line 106, in fit_transform
    step_inputs[input_step.name] = input_step.fit_transform(data)
  File "/home/user/robeson/unet/tensorX/open/open-solution-mapping-challenge-solution-6/src/steps/base.py", line 106, in fit_transform
    step_inputs[input_step.name] = input_step.fit_transform(data)
  File "/home/user/robeson/unet/tensorX/open/open-solution-mapping-challenge-solution-6/src/steps/base.py", line 106, in fit_transform
    step_inputs[input_step.name] = input_step.fit_transform(data)
  [Previous line repeated 3 more times]
  File "/home/user/robeson/unet/tensorX/open/open-solution-mapping-challenge-solution-6/src/steps/base.py", line 112, in fit_transform
    step_output_data = self._cached_fit_transform(step_inputs)
  File "/home/user/robeson/unet/tensorX/open/open-solution-mapping-challenge-solution-6/src/steps/base.py", line 124, in _cached_fit_transform
    step_output_data = self.transformer.fit_transform(**step_inputs)
  File "/home/user/robeson/unet/tensorX/open/open-solution-mapping-challenge-solution-6/src/steps/base.py", line 264, in fit_transform
    self.fit(*args, **kwargs)
  File "/home/user/robeson/unet/tensorX/open/open-solution-mapping-challenge-solution-6/src/models.py", line 79, in fit
    self.callbacks.on_batch_end(metrics=metrics)
  File "/home/user/robeson/unet/tensorX/open/open-solution-mapping-challenge-solution-6/src/steps/pytorch/callbacks.py", line 104, in on_batch_end
    callback.on_batch_end(*args, **kwargs)
  File "/home/user/robeson/unet/tensorX/open/open-solution-mapping-challenge-solution-6/src/steps/pytorch/callbacks.py", line 135, in on_batch_end
    loss = loss.data.cpu().numpy()[0]
IndexError: too many indices for array
`

Any one knows how to fix the bug?

**Comment by newcoder0531** [comment]
Have you solved this problem?

**Comment by robeson1010** [comment]
Yes, due to pytorch 0.4 
loss = loss.item()
