### ISSUE TITLE
pandas.errors.EmptyDataError: No columns to parse from file

### ISSUE THREAD

**Issue by carbonox-infernox** [neptune-ml/open-solution-mapping-challenge#177]
When I used the command `python main.py -- train --pipeline_name`,
I got the error:
Traceback (most recent call last):
  File "main.py", line 93, in <module>
    main()
  File "/home/derose/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/derose/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/derose/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/derose/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/derose/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 15, in prepare_masks
    pipeline_manager.prepare_masks(dev_mode)
  File "/home/derose/open-solution-mapping-challenge/src/pipeline_manager.py", line 26, in prepare_masks
    prepare_masks(dev_mode, self.logger, self.params)
  File "/home/derose/open-solution-mapping-challenge/src/pipeline_manager.py", line 61, in prepare_masks
    small_annotations_size=params.small_annotations_size)
  File "/home/derose/open-solution-mapping-challenge/src/preparation.py", line 28, in overlay_masks
    coco = COCO(annotation_file_path)
  File "/home/derose/anaconda3/lib/python3.6/site-packages/pycocotools/coco.py", line 79, in __init__
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '~/crowdai-mapping-challenge-mask-rcnn/data/train/annotation.json'

How can I fix this?

**Comment by taraspiotr** [comment]
Did you create the `metadata.csv` file and have the correct filepath to it?

**Comment by carbonox-infernox** [comment]
I'm not sure what you mean by prepare_metadata() method, but I earlier used the command:

python main.py -- prepare_metadata --train_data --valid_data --test_data

And i got the same issue as above. I'm trying to reproduce it now, but my commands are going to neptune and I can't get out of it.

**Comment by carbonox-infernox** [comment]
@taraspiotr I fixed an issue with my data path and updated the error message above. it is mostly the same, but it now includes
No such file or directory: '~/crowdai-mapping-challenge-mask-rcnn/data/train/annotation.json'
I don't know what to do about this, because the file is there.
