### ISSUE TITLE
Neptune keeps failing to upload

### ISSUE THREAD

**Issue by carbonox-infernox** [neptune-ml/open-solution-mapping-challenge#180]
The size of the dataset is crashing my system, so I'm trying to run this in Neptune. However, when I upload the files to Neptune it fails somewhere along the way, with the error:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/derose/anaconda3/lib/python3.6/site-packages/neptune/internal/common/api/utils.py", line 130, in func_wrapper
    return func(*args, **kwargs)
  File "/home/derose/anaconda3/lib/python3.6/site-packages/neptune/internal/common/api/utils.py", line 173, in func_wrapper
    raise NeptuneServerResponseErrorException(exc.status, exc)
neptune.internal.common.api.exceptions.NeptuneServerResponseErrorException: status: 500, response_message: Internal Server Error
2018-09-18 11:42:53,943 neptune.internal.common.api.utils ERROR    utils.py:126 - log_exception() Failed to call upload_data_as_tarstream
2018-09-18 11:42:53,944 neptune.internal.common.api.utils ERROR    utils.py:127 - log_exception() status: 500, response_message: Internal Server Error
Traceback (most recent call last):
  File "/home/derose/anaconda3/lib/python3.6/site-packages/neptune/internal/common/api/utils.py", line 157, in func_wrapper
    return func(*args, **kwargs)
  File "/home/derose/anaconda3/lib/python3.6/site-packages/neptune/internal/common/api/utils.py", line 194, in func_wrapper
    return func(*args, **dict(kwargs, headers_handler=headers_handler))
  File "/home/derose/anaconda3/lib/python3.6/site-packages/neptune/generated/swagger_client/apis/default_api.py", line 17183, in upload_data_as_tarstream
    headers_handler=params.get('headers_handler'))
  File "/home/derose/anaconda3/lib/python3.6/site-packages/neptune/generated/swagger_client/api_client.py", line 333, in call_api
    response_type, auth_settings, callback, headers_handler)
  File "/home/derose/anaconda3/lib/python3.6/site-packages/neptune/generated/swagger_client/api_client.py", line 155, in __call_api
    post_params=post_params, body=body)
  File "/home/derose/anaconda3/lib/python3.6/site-packages/neptune/generated/swagger_client/api_client.py", line 369, in request
    body=body)
  File "/home/derose/anaconda3/lib/python3.6/site-packages/neptune/generated/swagger_client/rest.py", line 164, in POST
    body=body)
  File "/home/derose/anaconda3/lib/python3.6/site-packages/neptune/generated/swagger_client/rest.py", line 132, in request
    raise ApiException(http_resp=r)
neptune.generated.swagger_client.rest.ApiException: (500)
Reason: Server Error
HTTP response headers: {'Server': 'nginx', 'Date': 'Tue, 18 Sep 2018 15:42:53 GMT', 'Content-Type': 'application/json;charset=utf-8', 'Transfer-Encoding': 'chunked', 'Via': '1.1 google', 'Alt-Svc': 'clear'}
HTTP response body: Internal Server Error

How can I fix this? I tried uploading files in smaller batches, but my folders were all separate (not under data) and Neptune apparently doesn't have a way to restructure anything after it's been uploaded. It seems like my only option is to upload everything in one go.

**Comment by hubertjaworskicodilime** [comment]
Hi,

Neptune team member here,

This error is not ideal and should be more informative, but it happens when the Neptune CLI can't read some of the files in the directory you're uploading.

Try changing access rights to the files you have so that a python process can successfully run os.path.getsize on all of them

Neptune site also have a web-based option do upload files - go to your project and select "Files" from the menu on the left, it could help for some access rights related issues

I can PM you with the exact file the CLI gets this error

Hope this helps,

Best regards,
Hubert

**Comment by carbonox-infernox** [comment]
Thanks, I ended up figuring out how to upload folders in pieces. I will try your solution though, because I uploaded a reduced portion of the images.

**Comment by kamil-kaczmarek** [comment]
Hi @carbonox-infernox,

By the end of this week, we will upload this dataset to the neptune `/public` directory. It means that you will be able to use it directly, without uploading the data by yourself.

I will let you know when this will be done.

Thank you,
Kamil Kaczmarek

**Comment by carbonox-infernox** [comment]
Awesome, thanks! I ended up using an EC2 instance since I knew i could get the local python version working, but I may switch to Neptune. The send pytorch gpu argument seems to imply that Neptune uses GPU acceleration. Is this true?

**Comment by hubertjaworskicodilime** [comment]
Hi,

Neptune can use GPUs (even multiple ones), but you need to sepecify it when sending your experiment.

You can select an [environement](https://docs.neptune.ml/advanced-topics/environments/) and a [workers](https://neptune.ml/pricing/#compute-resources) you wish to use

**Comment by carbonox-infernox** [comment]
I really want to do that to get this trained faster, but unfortunately I'm having a problem getting neptune to find files: #182

**Comment by carbonox-infernox** [comment]
@kamil-kaczmarek Since I saw you post recently I was wondering if i could ask you a quick question about preparing masks on Neptune. So far Neptune has been running for 4 hours and I can't find the masks_overlayed folder. in the .yaml I specified for it to go to /outputs, but I can't find this directory and Neptune is saying that I'm only using 3 GB of storage, which can't be right if the file is actually being generated.

**Comment by hubertjaworskicodilime** [comment]
Hi,

I think I can answer that - Neptune copies your /outputs only after the exprriment finishes, don't worry, it'll be there once the experiment is in state succeeded :)

**Comment by carbonox-infernox** [comment]
Awesome, thanks! I was thinking that might be the case.

**Comment by kamil-kaczmarek** [comment]
@jakubczakon how long does it take to prepare masks?
