### ISSUE TITLE
(Training model) IndexError: too many indices for array

### ISSUE THREAD

**Issue by carbonox-infernox** [neptune-ml/open-solution-mapping-challenge#183]
I ran the command python main.py -- train --pipeline_name unet_weighted and got the following error:

2018-09-19 21-14-06 steps >>> step xy_train adapting inputs

2018-09-19 21-14-06 steps >>> step xy_train transforming...

2018-09-19 21-14-06 steps >>> step xy_inference adapting inputs

2018-09-19 21-14-06 steps >>> step xy_inference transforming...

2018-09-19 21-14-06 steps >>> step loader adapting inputs

2018-09-19 21-14-06 steps >>> step loader transforming...

2018-09-19 21-14-06 steps >>> step unet unpacking inputs

2018-09-19 21-14-06 steps >>> step unet fitting and transforming...

2018-09-19 21-14-06 steps >>> starting training...

2018-09-19 21-14-06 steps >>> initial lr: 0.0005

2018-09-19 21-14-06 steps >>> epoch 0 ...

2018-09-19 21-14-08 steps >>> epoch 0 batch 0 ...

/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.

  warnings.warn(warning.format(ret))

Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7ff98110a6d8>>

Traceback (most recent call last):

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__

    self._shutdown_workers()

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers

    self.worker_result_queue.get()

  File "/home/ubuntu/anaconda3/lib/python3.6/multiprocessing/queues.py", line 337, in get

    return _ForkingPickler.loads(res)

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd

    fd = df.detach()

  File "/home/ubuntu/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach

    with _resource_sharer.get_connection(self._id) as conn:

  File "/home/ubuntu/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection

    c = Client(address, authkey=process.current_process().authkey)

  File "/home/ubuntu/anaconda3/lib/python3.6/multiprocessing/connection.py", line 493, in Client

    answer_challenge(c, authkey)

  File "/home/ubuntu/anaconda3/lib/python3.6/multiprocessing/connection.py", line 732, in answer_challenge

    message = connection.recv_bytes(256)         # reject large message

  File "/home/ubuntu/anaconda3/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes

    buf = self._recv_bytes(maxlength)

  File "/home/ubuntu/anaconda3/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes

    buf = self._recv(4)

  File "/home/ubuntu/anaconda3/lib/python3.6/multiprocessing/connection.py", line 383, in _recv

    raise EOFError

EOFError: 

Traceback (most recent call last):

  File "main.py", line 93, in <module>

    main()

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__

    return self.main(*args, **kwargs)

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main

    rv = self.invoke(ctx)

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke

    return callback(*args, **kwargs)

  File "main.py", line 31, in train

    pipeline_manager.train(pipeline_name, dev_mode)

  File "/home/ubuntu/open-solution-mapping-challenge/src/pipeline_manager.py", line 32, in train

    train(pipeline_name, dev_mode, self.logger, self.params, self.seed)

  File "/home/ubuntu/open-solution-mapping-challenge/src/pipeline_manager.py", line 116, in train

    pipeline.fit_transform(data)

  File "/home/ubuntu/open-solution-mapping-challenge/src/steps/base.py", line 106, in fit_transform

    step_inputs[input_step.name] = input_step.fit_transform(data)

  File "/home/ubuntu/open-solution-mapping-challenge/src/steps/base.py", line 106, in fit_transform

    step_inputs[input_step.name] = input_step.fit_transform(data)

  File "/home/ubuntu/open-solution-mapping-challenge/src/steps/base.py", line 106, in fit_transform

    step_inputs[input_step.name] = input_step.fit_transform(data)

  [Previous line repeated 3 more times]

  File "/home/ubuntu/open-solution-mapping-challenge/src/steps/base.py", line 112, in fit_transform

    return self._cached_fit_transform(step_inputs)

  File "/home/ubuntu/open-solution-mapping-challenge/src/steps/base.py", line 123, in _cached_fit_transform

    step_output_data = self.transformer.fit_transform(**step_inputs)

  File "/home/ubuntu/open-solution-mapping-challenge/src/steps/base.py", line 262, in fit_transform

    self.fit(*args, **kwargs)

  File "/home/ubuntu/open-solution-mapping-challenge/src/models.py", line 79, in fit

    self.callbacks.on_batch_end(metrics=metrics)

  File "/home/ubuntu/open-solution-mapping-challenge/src/steps/pytorch/callbacks.py", line 104, in on_batch_end

    callback.on_batch_end(*args, **kwargs)

  File "/home/ubuntu/open-solution-mapping-challenge/src/steps/pytorch/callbacks.py", line 135, in on_batch_end

    loss = loss.data.cpu().numpy()[0]

IndexError: too many indices for array

How can I fix this?

**Comment by newcoder0531** [comment]
if your torch version is 0.4.0,please use
`loss=loss.item()`

**Comment by carbonox-infernox** [comment]
Thank you! It's actually running now. One question though: After every batch I'm getting the warning

/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))

Training has only been running for a few minutes. Should I kill it and fix this issue so that it doesn't run for days and end up being garbage?
