### ISSUE TITLE
Error: No module named 'Cython'

### ISSUE THREAD

**Issue by cvKDean** [neptune-ml/open-solution-mapping-challenge#214]
Good day,

I am trying to install the updated repository. In `REPRODUCE_RESULTS.md`, I have cloned the repository using `git clone https://github.com/minerva-ml/open-solution-mapping-challenge.git` and tried to install the conda environment `mapping`. 

Command used is 
`conda env create -f environment.yml`

Terminal shows:
```
Collecting pycocotools==2.0.0 (from -r /home/deankarlo/Thesis Files/ML Models/open-solution-mapping-challenge/condaenv.aog2chrg.requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/96/84/9a07b1095fd8555ba3f3d519517c8743c2554a245f9476e5e39869f948d2/pycocotools-2.0.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qfw088ke/pycocotools/setup.py", line 2, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-qfw088ke/pycocotools/

CondaValueError: pip returned an error
```
When installing `pycocotools` it seems to be looking for `Cython`.

**Comment by cvKDean** [comment]
Solved by renaming `cython` to `Cython` in the `environment.yaml` file.
Not sure if there is any difference in the dependencies but it fixed the `pycocotools` errors for me.
